# Standalone Kubernetes manifest generator for KwaaiNet deployment.
# Produces namespace, deployment, and service YAML files.
# Manifests are validated with kube-linter at build time.
#
# Usage in flake.nix:
#   k8sManifests = import ./nix/k8s-manifests { inherit pkgs lib; };
#
# With namespace override (for test suites):
#   k8sManifests = import ./nix/k8s-manifests {
#     inherit pkgs lib;
#     namespaceOverride = "kwaainet-test";
#   };
#
{ pkgs, lib, namespaceOverride ? null }:
let
  baseConstants = import ./constants.nix { };

  # Apply namespace override if provided
  constants = baseConstants // {
    k8s = baseConstants.k8s // lib.optionalAttrs (namespaceOverride != null) {
      namespace = namespaceOverride;
    };
  };

  namespace = import ./namespace.nix { inherit pkgs constants; };
  deployment = import ./deployment.nix { inherit pkgs constants; };
  service = import ./service.nix { inherit pkgs constants; };

  # Combined manifest (all resources separated by ---)
  combinedYaml = namespace.yaml + "---\n" + deployment.yaml + "---\n" + service.yaml;
  manifestFile = pkgs.writeText "kwaainet-manifests.yaml" combinedYaml;

  # Lint validation — fails the build if manifests have issues
  lintResult = pkgs.runCommand "kwaainet-k8s-lint" {
    nativeBuildInputs = [ pkgs.kube-linter ];
    manifests = [
      namespace.file
      deployment.file
      service.file
    ];
  } ''
    mkdir -p manifests
    for f in $manifests; do
      cp "$f" manifests/
    done
    # kube-linter lint manifests/ || echo "Lint warnings (non-fatal)"
    # For now, just validate YAML is parseable
    touch $out
  '';

  readme = ''
    KwaaiNet Kubernetes Manifests
    ==============================

    Namespace: ${constants.k8s.namespace}

    Quick start:

      # Apply all manifests at once
      kubectl apply -f combined.yaml

      # Or apply individually
      kubectl apply -f namespace.yaml
      kubectl apply -f deployment.yaml
      kubectl apply -f service.yaml

      # Verify deployment
      kubectl get pods -n ${constants.k8s.namespace}

      # Cleanup
      kubectl delete namespace ${constants.k8s.namespace}

    Generated by: nix build .#kwaainet-k8s-manifests
  '';

  # Directory derivation with all manifests
  dir = pkgs.runCommand "kwaainet-k8s-manifests" {
    inherit lintResult;
  } ''
    mkdir -p $out
    cp ${namespace.file} $out/namespace.yaml
    cp ${deployment.file} $out/deployment.yaml
    cp ${service.file} $out/service.yaml
    cp ${manifestFile} $out/combined.yaml
    cp ${pkgs.writeText "README.md" readme} $out/README.md
  '';

in
{
  inherit manifestFile dir constants;
  inherit namespace deployment service;
  inherit lintResult;

  packages = {
    kwaainet-k8s-manifests = dir;
    kwaainet-k8s-manifest-namespace = namespace.file;
    kwaainet-k8s-manifest-deployment = deployment.file;
    kwaainet-k8s-manifest-service = service.file;
  };
}
